# Generated by Django 5.2.5 on 2026-05-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('restaurant_description', models.TextField(blank=True, null=True)),
                ('restaurant_address', models.CharField(blank=True, max_length=500, null=True)),
                ('restaurant_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('restaurant_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('delivery_fee', models.PositiveIntegerField(default=1500)),
                ('accept_orders', models.BooleanField(default=True)),
                ('accept_reservations', models.BooleanField(default=True)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurant Settings',
                'verbose_name_plural': 'Restaurant Settings',
            },
        ),
    ]
