# Generated by Django 5.2.5 on 2026-05-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('food', 'Food'), ('ambiance', 'Ambiance'), ('events', 'Events'), ('bakery', 'Bakery')], default='food', max_length=50)),
                ('storage_path', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
