# Generated by Django 5.2.5 on 2026-05-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('ambiance', 'Ambiance'), ('events', 'Events'), ('catering', 'Catering'), ('behind_the_scenes', 'Behind the Scenes')], default='food', max_length=50),
        ),
    ]
